version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo "Deploying Flask backend to EC2"
  post_build:
    commands:
      - |
        ssh -o StrictHostKeyChecking=no ec2-user@YOUR_EC2_PUBLIC_DNS << 'EOF'
        cd /home/ec2-user/stock-backend
        git pull origin main
        source venv/bin/activate
        pip install -r requirements.txt
        sudo systemctl restart flaskapp
        EOF
