version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.11
    commands:
      - echo "Installing dependencies for frontend and backend"
      - pip install awscli

  build:
    commands:
      - echo "Building React frontend"
      - cd frontend
      - npm install
      - npm run build
      - cd ..

  post_build:
    commands:
      - echo "Deploying frontend to S3"
      - aws s3 sync frontend/build/ s3://stocktrackerappartifact --delete

      - echo "Fetching EC2 instance IDs"
      - |
        INSTANCE_IDS=$(aws autoscaling describe-auto-scaling-groups \
          --auto-scaling-group-name backend-asg \
          --query "AutoScalingGroups[].Instances[].InstanceId" \
          --output text)
        echo "Found INSTANCE_IDS: $INSTANCE_IDS"

      - echo "Deploying backend using SSM RunCommand"
      - |
        for id in $INSTANCE_IDS; do
          echo "Sending deployment command to $id"
          aws ssm send-command \
            --instance-ids "$id" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy updated Flask backend" \
            --parameters commands='[
              "cd /home/ec2-user",
              "sudo yum install -y git",
              "sudo git clone https://github.com/umass-sriram/stock-tracker.git stock-backend",
              "sudo cd stock-backend",
              "if [ ! -d venv ]; then python3 -m venv venv; fi",
              "source venv/bin/activate",
              "pip install --upgrade pip",
              "pip install -r requirements.txt",
              "sudo systemctl restart flaskapp || echo Service not found"
            ]' \
            --region us-east-1
        done

artifacts:
  files:
    - '**/*'
