version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.11
    commands:
      - echo "Installing dependencies for frontend and backend"
      - pip install awscli

  build:
    commands:
      - echo "Building React frontend"
      - cd frontend
      - npm install
      - npm run build
      - cd ..

  post_build:
    commands:
      - echo "Deploying frontend to S3"
      - aws s3 sync frontend/build/ s3://stocktrackerappartifact --delete

      - echo "Deploying backend using SSM RunCommand"
      - |
        bash -c '
        INSTANCE_IDS=$(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-name backend-asg --query "AutoScalingGroups[].Instances[].InstanceId" --output text)
        echo "Found INSTANCE_IDS: $INSTANCE_IDS"

        for id in $INSTANCE_IDS; do
          echo "Sending deployment command to $id"
          aws ssm send-command --instance-ids "$id" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy updated Flask backend" \
            --parameters commands=[
              "cd /home/ec2-user",
              "sudo yum install -y git",
              "cd /home/ec2-user",
              "if [ ! -d stock-backend ]; then git clone https://github.com/umass-sriram/stock-tracker.git stock-backend; fi",
              "cd stock-backend",
              "git pull origin main",
              "if [ ! -d venv ]; then python3 -m venv venv; fi",
              "
